##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.3.0-B58] date: [Wed Apr 23 12:18:38 EDT 2025]
# Generic Makefile (based on gcc)
##########################################################################################################################
# Makefile originally created by CubeMx but maintained by hand
# after the original file was created.
##########################################################################################################################

ifndef OBJ_BLD_ROOT
OBJ_BLD_ROOT = .
endif

TARGET = saturn_wave_fwr

BUILD_DIR_OBJ = $(OBJ_BLD_ROOT)/bld_$(TARGET)_obj
BUILD_DIR_OUT = bld_$(TARGET)_output

# building variables
# debug build?
DEBUG = 1
# optimization
OPT = -Og
# OPT = -O2

## -fdebug-prefix-map=/full/build/path=.

C_SOURCES :=  \
$(wildcard Core/Src/*.c) \
$(wildcard Utilities/*.c) \
$(wildcard App/Src/*.c) \
$(wildcard Middlewares/ST/STM32_WPAN/Src/*.c) \
$(wildcard STM32_WPAN/App/*.c) \
$(wildcard Hal/Src/*.c) \
Drivers/BSP/P-NUCLEO-WB55.Nucleo/stm32wbxx_nucleo.c \
Middlewares/ST/threadx/common/src/tx_initialize_high_level.c \
Middlewares/ST/threadx/common/src/tx_initialize_kernel_enter.c \
Middlewares/ST/threadx/common/src/tx_initialize_kernel_setup.c \
Middlewares/ST/threadx/common/src/tx_block_allocate.c \
Middlewares/ST/threadx/common/src/tx_block_pool_cleanup.c \
Middlewares/ST/threadx/common/src/tx_block_pool_create.c \
Middlewares/ST/threadx/common/src/tx_block_pool_delete.c \
Middlewares/ST/threadx/common/src/tx_block_pool_info_get.c \
Middlewares/ST/threadx/common/src/tx_block_pool_initialize.c \
Middlewares/ST/threadx/common/src/tx_block_pool_prioritize.c \
Middlewares/ST/threadx/common/src/tx_block_release.c \
Middlewares/ST/threadx/common/src/tx_byte_allocate.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_cleanup.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_create.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_delete.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_info_get.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_initialize.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_prioritize.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_search.c \
Middlewares/ST/threadx/common/src/tx_byte_release.c \
Middlewares/ST/threadx/common/src/tx_event_flags_cleanup.c \
Middlewares/ST/threadx/common/src/tx_event_flags_create.c \
Middlewares/ST/threadx/common/src/tx_event_flags_delete.c \
Middlewares/ST/threadx/common/src/tx_event_flags_get.c \
Middlewares/ST/threadx/common/src/tx_event_flags_info_get.c \
Middlewares/ST/threadx/common/src/tx_event_flags_initialize.c \
Middlewares/ST/threadx/common/src/tx_event_flags_set.c \
Middlewares/ST/threadx/common/src/tx_event_flags_set_notify.c \
Middlewares/ST/threadx/common/src/tx_mutex_cleanup.c \
Middlewares/ST/threadx/common/src/tx_mutex_create.c \
Middlewares/ST/threadx/common/src/tx_mutex_delete.c \
Middlewares/ST/threadx/common/src/tx_mutex_get.c \
Middlewares/ST/threadx/common/src/tx_mutex_info_get.c \
Middlewares/ST/threadx/common/src/tx_mutex_initialize.c \
Middlewares/ST/threadx/common/src/tx_mutex_prioritize.c \
Middlewares/ST/threadx/common/src/tx_mutex_priority_change.c \
Middlewares/ST/threadx/common/src/tx_mutex_put.c \
Middlewares/ST/threadx/common/src/tx_queue_cleanup.c \
Middlewares/ST/threadx/common/src/tx_queue_create.c \
Middlewares/ST/threadx/common/src/tx_queue_delete.c \
Middlewares/ST/threadx/common/src/tx_queue_flush.c \
Middlewares/ST/threadx/common/src/tx_queue_front_send.c \
Middlewares/ST/threadx/common/src/tx_queue_info_get.c \
Middlewares/ST/threadx/common/src/tx_queue_initialize.c \
Middlewares/ST/threadx/common/src/tx_queue_prioritize.c \
Middlewares/ST/threadx/common/src/tx_queue_receive.c \
Middlewares/ST/threadx/common/src/tx_queue_send.c \
Middlewares/ST/threadx/common/src/tx_queue_send_notify.c \
Middlewares/ST/threadx/common/src/tx_semaphore_ceiling_put.c \
Middlewares/ST/threadx/common/src/tx_semaphore_cleanup.c \
Middlewares/ST/threadx/common/src/tx_semaphore_create.c \
Middlewares/ST/threadx/common/src/tx_semaphore_delete.c \
Middlewares/ST/threadx/common/src/tx_semaphore_get.c \
Middlewares/ST/threadx/common/src/tx_semaphore_info_get.c \
Middlewares/ST/threadx/common/src/tx_semaphore_initialize.c \
Middlewares/ST/threadx/common/src/tx_semaphore_prioritize.c \
Middlewares/ST/threadx/common/src/tx_semaphore_put.c \
Middlewares/ST/threadx/common/src/tx_semaphore_put_notify.c \
Middlewares/ST/threadx/common/src/tx_thread_create.c \
Middlewares/ST/threadx/common/src/tx_thread_delete.c \
Middlewares/ST/threadx/common/src/tx_thread_entry_exit_notify.c \
Middlewares/ST/threadx/common/src/tx_thread_identify.c \
Middlewares/ST/threadx/common/src/tx_thread_info_get.c \
Middlewares/ST/threadx/common/src/tx_thread_initialize.c \
Middlewares/ST/threadx/common/src/tx_thread_preemption_change.c \
Middlewares/ST/threadx/common/src/tx_thread_priority_change.c \
Middlewares/ST/threadx/common/src/tx_thread_relinquish.c \
Middlewares/ST/threadx/common/src/tx_thread_reset.c \
Middlewares/ST/threadx/common/src/tx_thread_resume.c \
Middlewares/ST/threadx/common/src/tx_thread_shell_entry.c \
Middlewares/ST/threadx/common/src/tx_thread_sleep.c \
Middlewares/ST/threadx/common/src/tx_thread_stack_analyze.c \
Middlewares/ST/threadx/common/src/tx_thread_stack_error_handler.c \
Middlewares/ST/threadx/common/src/tx_thread_stack_error_notify.c \
Middlewares/ST/threadx/common/src/tx_thread_suspend.c \
Middlewares/ST/threadx/common/src/tx_thread_system_preempt_check.c \
Middlewares/ST/threadx/common/src/tx_thread_system_resume.c \
Middlewares/ST/threadx/common/src/tx_thread_system_suspend.c \
Middlewares/ST/threadx/common/src/tx_thread_terminate.c \
Middlewares/ST/threadx/common/src/tx_thread_time_slice.c \
Middlewares/ST/threadx/common/src/tx_thread_time_slice_change.c \
Middlewares/ST/threadx/common/src/tx_thread_timeout.c \
Middlewares/ST/threadx/common/src/tx_thread_wait_abort.c \
Middlewares/ST/threadx/common/src/tx_time_get.c \
Middlewares/ST/threadx/common/src/tx_time_set.c \
Middlewares/ST/threadx/common/src/txe_block_allocate.c \
Middlewares/ST/threadx/common/src/txe_block_pool_create.c \
Middlewares/ST/threadx/common/src/txe_block_pool_delete.c \
Middlewares/ST/threadx/common/src/txe_block_pool_info_get.c \
Middlewares/ST/threadx/common/src/txe_block_pool_prioritize.c \
Middlewares/ST/threadx/common/src/txe_block_release.c \
Middlewares/ST/threadx/common/src/txe_byte_allocate.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_create.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_delete.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_info_get.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_prioritize.c \
Middlewares/ST/threadx/common/src/txe_byte_release.c \
Middlewares/ST/threadx/common/src/txe_event_flags_create.c \
Middlewares/ST/threadx/common/src/txe_event_flags_delete.c \
Middlewares/ST/threadx/common/src/txe_event_flags_get.c \
Middlewares/ST/threadx/common/src/txe_event_flags_info_get.c \
Middlewares/ST/threadx/common/src/txe_event_flags_set.c \
Middlewares/ST/threadx/common/src/txe_event_flags_set_notify.c \
Middlewares/ST/threadx/common/src/txe_mutex_create.c \
Middlewares/ST/threadx/common/src/txe_mutex_delete.c \
Middlewares/ST/threadx/common/src/txe_mutex_get.c \
Middlewares/ST/threadx/common/src/txe_mutex_info_get.c \
Middlewares/ST/threadx/common/src/txe_mutex_prioritize.c \
Middlewares/ST/threadx/common/src/txe_mutex_put.c \
Middlewares/ST/threadx/common/src/txe_queue_create.c \
Middlewares/ST/threadx/common/src/txe_queue_delete.c \
Middlewares/ST/threadx/common/src/txe_queue_flush.c \
Middlewares/ST/threadx/common/src/txe_queue_front_send.c \
Middlewares/ST/threadx/common/src/txe_queue_info_get.c \
Middlewares/ST/threadx/common/src/txe_queue_prioritize.c \
Middlewares/ST/threadx/common/src/txe_queue_receive.c \
Middlewares/ST/threadx/common/src/txe_queue_send.c \
Middlewares/ST/threadx/common/src/txe_queue_send_notify.c \
Middlewares/ST/threadx/common/src/txe_semaphore_ceiling_put.c \
Middlewares/ST/threadx/common/src/txe_semaphore_create.c \
Middlewares/ST/threadx/common/src/txe_semaphore_delete.c \
Middlewares/ST/threadx/common/src/txe_semaphore_get.c \
Middlewares/ST/threadx/common/src/txe_semaphore_info_get.c \
Middlewares/ST/threadx/common/src/txe_semaphore_prioritize.c \
Middlewares/ST/threadx/common/src/txe_semaphore_put.c \
Middlewares/ST/threadx/common/src/txe_semaphore_put_notify.c \
Middlewares/ST/threadx/common/src/txe_thread_create.c \
Middlewares/ST/threadx/common/src/txe_thread_delete.c \
Middlewares/ST/threadx/common/src/txe_thread_entry_exit_notify.c \
Middlewares/ST/threadx/common/src/txe_thread_info_get.c \
Middlewares/ST/threadx/common/src/txe_thread_preemption_change.c \
Middlewares/ST/threadx/common/src/txe_thread_priority_change.c \
Middlewares/ST/threadx/common/src/txe_thread_relinquish.c \
Middlewares/ST/threadx/common/src/txe_thread_reset.c \
Middlewares/ST/threadx/common/src/txe_thread_resume.c \
Middlewares/ST/threadx/common/src/txe_thread_suspend.c \
Middlewares/ST/threadx/common/src/txe_thread_terminate.c \
Middlewares/ST/threadx/common/src/txe_thread_time_slice_change.c \
Middlewares/ST/threadx/common/src/txe_thread_wait_abort.c \
Middlewares/ST/threadx/common/src/tx_timer_activate.c \
Middlewares/ST/threadx/common/src/tx_timer_change.c \
Middlewares/ST/threadx/common/src/tx_timer_create.c \
Middlewares/ST/threadx/common/src/tx_timer_deactivate.c \
Middlewares/ST/threadx/common/src/tx_timer_delete.c \
Middlewares/ST/threadx/common/src/tx_timer_expiration_process.c \
Middlewares/ST/threadx/common/src/tx_timer_info_get.c \
Middlewares/ST/threadx/common/src/tx_timer_initialize.c \
Middlewares/ST/threadx/common/src/tx_timer_system_activate.c \
Middlewares/ST/threadx/common/src/tx_timer_system_deactivate.c \
Middlewares/ST/threadx/common/src/tx_timer_thread_entry.c \
Middlewares/ST/threadx/common/src/txe_timer_activate.c \
Middlewares/ST/threadx/common/src/txe_timer_change.c \
Middlewares/ST/threadx/common/src/txe_timer_create.c \
Middlewares/ST/threadx/common/src/txe_timer_deactivate.c \
Middlewares/ST/threadx/common/src/txe_timer_delete.c \
Middlewares/ST/threadx/common/src/txe_timer_info_get.c \
#Hal/Src/gpio.c \
# Core/Src/main.c \

# C_SOURCES +=  \
# App/Src/CmdRespProtocol.c \
# App/Src/CommandHandler.c \
# App/Src/Crc16.c \
# App/Src/Emg.c \
# App/Src/TimedEvent.c \
# AZURE_RTOS/App/app_azure_rtos.c \
# Core/Src/app_threadx.c \
# Core/Src/dma.c \
# Core/Src/ErrorHandler.c \
# Core/Src/stm32f4xx_hal_msp.c \
# Core/Src/stm32f4xx_hal_timebase_tim.c \
# Core/Src/stm32f4xx_it.c \
# Core/Src/system_stm32f4xx.c \
# Hal/Src/Ads1298.c \
# Hal/Src/AfePowerCtrl.c \
# Hal/Src/AfeSpi.c \
# Hal/Src/Gpio.c \
# Hal/Src/HalMspInitDeint.c \
# Hal/Src/SerialInterface.c

CPP_SOURCES +=  \
$(wildcard Core/Src/*.cpp) \
$(wildcard App/Src/*.cpp) \
$(wildcard Hal/Src/*.cpp)

#THREADX_RTOS_SUB_ROOT = Middlewares/ST/threadx
#include $(THREADX_RTOS_SUB_ROOT)/ThreadXRtosInc.mk

ifdef FREE_RTOS_INC
# Include for FreeRTOS sources and includes
FREE_RTOS_SUB_ROOT = Middlewares/Third_Party/FreeRTOS/Source
include $(FREE_RTOS_SUB_ROOT)/FreeRtosInc.mk
endif


# Include for HAL Driver sources and includes
HAL_DRV_SUB_ROOT = Drivers/STM32WBxx_HAL_Driver
CMSIS_DRV_SUB_ROOT = Drivers/CMSIS
include $(HAL_DRV_SUB_ROOT)/STM32WBxxHalDriverInc.mk

ASM_STARTUP_CODE_PATH = .
ASM_SOURCES +=  \
$(ASM_STARTUP_CODE_PATH)/startup_stm32wb55rgvx.s

ASM_SOURCES +=  \
Core/Src/tx_initialize_low_level.s

# ASM sources
ASMM_SOURCES = \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_misra.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_context_restore.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_context_save.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_interrupt_control.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_interrupt_disable.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_interrupt_restore.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_schedule.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_stack_build.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_system_return.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_timer_interrupt.S

#######################################
# binaries
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
CPP = $(GCC_PATH)/$(PREFIX)g++
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
CPP = $(PREFIX)g++
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

#######################################
# Defines
# C defines - Common defines for all boards
C_DEFS =  \
-DTX_INCLUDE_USER_DEFINE_FILE \
-DUSE_FULL_ASSERT=1 \
-DUSE_HAL_DRIVER \
-DUSE_STM32WBXX_NUCLEO \
-DTX_INCLUDE_USER_DEFINE_FILE

ifdef BAUD_RATE
C_DEFS += -DBAUD_RATE=$(BAUD_RATE)
endif

# C defines - Board specific defines
C_DEFS += \
-DSTM32WB55xx

# AS includes
AS_INCLUDES =  \
-ICore\Inc

# C includes
C_INCLUDES +=  \
-IApp/Inc \
-ICore/Inc \
-IHal/Inc \
-IUtilities \
-IMiddlewares/ST/STM32_WPAN/Inc/ble \
-IMiddlewares/ST/STM32_WPAN/Inc \
-IMiddlewares/ST/STM32_WPAN/Inc/interface/patterns/ble_thread \
-IMiddlewares/ST/STM32_WPAN/Inc/interface/patterns/ble_thread/tl \
-IMiddlewares/ST/STM32_WPAN/Inc/interface/patterns/ble_thread/shci \
-IMiddlewares/ST/STM32_WPAN/Inc/utilities \
-IMiddlewares/ST/STM32_WPAN/Inc/ble/core \
-IMiddlewares/ST/STM32_WPAN/Inc/ble/core/auto \
-IMiddlewares/ST/STM32_WPAN/Inc/ble/core/template \
-IMiddlewares/ST/STM32_WPAN/Inc/ble/svc/Inc \
-IMiddlewares/ST/STM32_WPAN/Inc/ble/svc/Src \
-ISTM32_WPAN/App \
-IDrivers/BSP/P-NUCLEO-WB55.Nucleo \
-IMiddlewares/ST/threadx/ports/cortex_m4/gnu/inc/ \
-IMiddlewares/ST/threadx/common/inc/ \
-IMiddlewares/ST/threadx/utility/low_power/ \

#######################################
# Compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections
CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CPPFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections
CPPFLAGS += -std=c++17 -fno-rtti -fno-exceptions -lstdc++

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2 
CPPFLAGS += -g3 -gdwarf-2
endif

# C Flags to generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# Link script (loader)
LDSCRIPT = STM32WB55RGVX_FLASH.ld

#######################################
# Libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -specs=nosys.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR_OBJ)/$(TARGET).map,--cref -Wl,--gc-sections -u _printf_float
# LDFLAGS = $(MCU) -specs=nano.specs                  -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(EXE_DIR)/$(TARGET).map,      --cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR_OUT)/$(TARGET).elf $(BUILD_DIR_OUT)/$(TARGET).hex $(BUILD_DIR_OUT)/$(TARGET).bin

echo: 
	echo $(PWD)

#######################################
# build the application
# list of C objects
OBJECTS = $(addprefix $(BUILD_DIR_OBJ)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of C++ objects
OBJECTS += $(addprefix $(BUILD_DIR_OBJ)/,$(notdir $(CPP_SOURCES:.cpp=.o)))
vpath %.cpp $(sort $(dir $(CPP_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR_OBJ)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
# list of ASM Capital S objects
OBJECTS += $(addprefix $(BUILD_DIR_OBJ)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR_OBJ)/%.o: %.c Makefile | $(BUILD_DIR_OBJ) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR_OBJ)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR_OBJ)/%.o: %.cpp Makefile | $(BUILD_DIR_OBJ) 
	$(CPP) -c $(CPPFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR_OBJ)/$(notdir $(<:.cpp=.lst)) $< -o $@

$(BUILD_DIR_OBJ)/%.o: %.s Makefile | $(BUILD_DIR_OBJ)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR_OBJ)/%.o: %.S Makefile | $(BUILD_DIR_OBJ)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR_OUT)/$(TARGET).elf: $(OBJECTS) Makefile $(BUILD_DIR_OUT)
	$(CPP) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR_OUT)/%.hex: $(BUILD_DIR_OUT)/%.elf | $(BUILD_DIR_OUT)
	$(HEX) $< $@
	
$(BUILD_DIR_OUT)/%.bin: $(BUILD_DIR_OUT)/%.elf | $(BUILD_DIR_OUT)
	$(BIN) $< $@	
	
$(BUILD_DIR_OBJ):
	mkdir -p $@		

$(BUILD_DIR_OUT):
	mkdir -p $@		

#######################################
# clean up
clean:
	-rm -fR $(BUILD_DIR_OBJ)
	-rm -fR $(BUILD_DIR_OUT)
  
#######################################
# dependencies
-include $(wildcard $(BUILD_DIR_OBJ)/*.d)
